### PR TITLE
Sonic Adventure DX (steam): add alternative save location

### PR DESCRIPTION
**Pull request by soredake**
This mod https://sadxmodinstaller.unreliable.network/ downgrades exe and this changing save data location.

### CODE REVIEW

**Comment by mtkennerly** [comment]
Thanks for the PR! Because of how the manifest is updated, these changes could be wiped out later since they won't match what's on PCGamingWiki. I imagine PCGW probably doesn't want mod paths in their main save/config tables, so I think we would need to add another file to the repo, like data/manifest-supplement.yaml, for this info. The supplement file could then be combined into the main file when performing the daily updates.

If you're interested in implementing the supplement file, let me know, but otherwise I'll try to add it as soon as I have some time so that we can add this save info there.

**Comment by darklinkpower** [comment]
I think it should be fine using the same main entry and just adding a proper note that this is the directory when using the mod. For example, in this entry I added the mod to the entry and also added the save path: https://www.pcgamingwiki.com/wiki/Umineko_When_They_Cry_-_Question_Arcs#Save_game_data_location

Although it should be better to ask the PCGW staff about this.

**Comment by soredake** [comment]
I've updated pcgamingwiki page https://www.pcgamingwiki.com/wiki/Sonic_Adventure_DX_(Steam)#Configuration_file.28s.29_location

**Comment by soredake** [comment]
Merged https://github.com/mtkennerly/ludusavi-manifest/commit/046affcbbe36c730ad3bf30f7efd7c5693d37c91#diff-86b38c85c292f5a5025e585057a4d546R214491-R214495

**Pull request closed without merging**
